DROP TABLE IF EXISTS InappropriatesWords; 
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS PhotosCategories;
DROP TABLE IF EXISTS Ratings;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Photos;
DROP TABLE IF EXISTS Users;


CREATE TABLE Users (
	userId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	surname VARCHAR(100) NOT NULL,
	telephone CHAR(9) NOT NULL,
	username VARCHAR(40) NOT NULL UNIQUE,
	password VARCHAR(300) NOT NULL,
	profilePhoto VARCHAR(300),
	email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Photos (
	photoId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(128) NOT NULL,
	description VARCHAR(512),
	date DATETIME DEFAULT CURRENT_TIMESTAMP,
	url VARCHAR(512) NOT NULL,
	visibility VARCHAR(16) NOT NULL,
	userId INT NOT NULL,
	FOREIGN KEY(userId) REFERENCES Users(userId),
	CONSTRAINT ValidVisibility CHECK (visibility in ('Public', 'Private'))
);

CREATE TABLE Ratings (
	ratingId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	date DATETIME DEFAULT CURRENT_TIMESTAMP,
	value INT NOT NULL,
	userId INT NOT NULL,
	photoId INT NOT NULL,
	FOREIGN KEY(userId) REFERENCES Users(userId) ON DELETE CASCADE,
	FOREIGN KEY(photoId) REFERENCES Photos(photoId) ON DELETE CASCADE,
	UNIQUE(userId, photoId)
);

CREATE TABLE Categories (
	categoryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(15) NOT NULL
);

CREATE TABLE PhotosCategories (
	photoCategoryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	photoId INT NOT NULL,
	categoryId INT NOT NULL,
	FOREIGN KEY(photoId) REFERENCES Photos(photoId) ON DELETE CASCADE,
	FOREIGN KEY(categoryId) REFERENCES Categories(CategoryId),
	UNIQUE(photoId, categoryId)
);

CREATE TABLE Comments (
	commentId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	text VARCHAR(300) NOT NULL,
	date DATETIME DEFAULT CURRENT_TIMESTAMP,
	photoId INT NOT NULL,
	userId INT NOT NULL,
	FOREIGN KEY(photoId) REFERENCES Photos(PhotoId),
	FOREIGN KEY(userId) REFERENCES Users(userId)
);

CREATE TABLE InappropriatesWords (
	InappropriateWordId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	word VARCHAR(50) NOT NULL UNIQUE
);

